<a href="https://colab.research.google.com/github/Ernozkn/NUMPY-UYGULAMA-EREN-ZKAN/blob/main/NUMPY_UYGULAMA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np
print(np.__version__)


2.0.2


1.SORU

In [ ]:
# 1 den 10 a kadar olan sayılar
dizi = np.array([1,2,3,4,5,6,7,8,9])
print(dizi)

[1 2 3 4 5 6 7 8 9]


2.SORU

In [ ]:
# 5 elemanlı sıfırlardan oluşan bir dizi
dizi = np.zeros(5)
print(dizi)

[0. 0. 0. 0. 0.]


In [ ]:
# 3x3'lük birler matrisi
dizi = np.ones((3, 3))
print(dizi)

In [ ]:
# 10 ile 20 arasında artan bir dizi
dizi = np.arange(10, 21)
print(dizi)

3.SORU

In [ ]:
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
eleman = arr[1][2]
print(eleman)

30


4.SORU

In [ ]:
alt_dizi = arr[:, 0:2]
print(alt_dizi)

5.SORU

In [ ]:
print(arr.dtype)
# Diziyi float türüne dönüştür
arr_float = arr.astype(float)
print(arr_float.dtype)


int64
float64


6.SORU

In [ ]:

# Orijinal dizi
arr = np.array([10, 20, 30, 40])

# Kopya oluştur
arr_copy = arr.copy()

# View (görünüm) oluştur
arr_view = arr.view()

# Kopyada değişiklik yap
arr_copy[0] = 999

# View'da değişiklik yap
arr_view[1] = 888

# Hepsini yazdır
print("Orijinal dizi:", arr)
print("Kopya dizi:", arr_copy)
print("View dizi:", arr_view)


Orijinal dizi: [ 10 888  30  40]
Kopya dizi: [999  20  30  40]
View dizi: [ 10 888  30  40]


7.SORU

In [ ]:
# 3x4 boyutunda bir NumPy dizisi oluştur
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Dizi boyutlarını yazdır
print("Dizinin boyutları:", arr.shape)


Dizinin boyutları: (3, 4)


8.SORU

In [ ]:
# 1'den 12'ye kadar olan sayılardan oluşan dizi oluştur (1 dahil, 13 hariç)
arr = np.arange(1, 13)

# 3x4 boyutunda matrise dönüştür
matrix = arr.reshape(3, 4)

# Matrisi yazdır
print("3x4 Matris:\n", matrix)


3x4 Matris:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


9.SORU

In [ ]:
# 2 boyutlu NumPy dizisi
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Satır satır döngü
for row in arr:
    for elem in row:
        print(elem, end=' ')
    print()  # Satır sonu için boş print


1 2 3 
4 5 6 
7 8 9 


10.SORU

In [ ]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])
birleştirme = np.concatenate((a, b), axis=0)
print("Dikey birleştirme:\n", birleştirme)


Dikey birleştirme:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


11.SORU

In [ ]:
# 1'den 12'ye kadar olan dizi (1 dahil, 13 hariç)
arr = np.arange(1, 13)

# 3 eşit parçaya böl
bölme = np.split(arr, 3)

print("3 eşit parçaya bölünmüş dizi:",bölme)


3 eşit parçaya bölünmüş dizi: [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


12.SORU

In [ ]:
arr = np.array([10, 15, 20, 25, 30])
# 25 in indeks değerini buldurur
bulma = np.where(arr == 25)
print("Aranan elemanın indeks numarası:",bulma)

Aranan elemanın indeks numarası: (array([3]),)


13.SORU

In [ ]:
arr = np.array([42, 17, 8, 99, 23])
# Sayıları küçükten büyüğe sıralar
sıralı_dizi = np.sort(arr)
print("Sıralı dizi:", sıralı_dizi)

Sıralı dizi: [ 8 17 23 42 99]


14.SORU

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
# çift sayıları bulur
cift_sayılar = arr[arr % 2 == 0]
print("Çift sayılar:", cift_sayılar)

Çift sayılar: [2 4 6]
